### RECUPERAR TODAS LAS PELICULAS
GET http://localhost:1234/movies

### RECUPERAR UNA PELICULA POR ID
GET http://localhost:1234/movies/8fb17ae1-bdfe-45e5-a871-4772d7e526b8

### RECUPERAR TODAS LAS PELICULAS POR UN GENERO
GET http://localhost:1234/movies?genre=Action

### CREAR UNA PELICULA CON POST
POST http://localhost:1234/movies